base_url = "https://esimmler.com"
generate_rss = true
compile_sass = true
highlight_code = true
highlight_theme = "cheerfully-light"
build_search_index = false
title = "Erik Simmler"

[extra]
author = "Erik Simmler"
rss_path = "/rss.xml"
