flags: {}
extra-package-dbs: []
packages:
- .
extra-deps: []
resolver: lts-9.14
docker:
  enable: true
image:
  containers:
    -
      base: "fpco/ubuntu-with-libgmp:14.04"
      name: "tgecho/esimmler-com"