version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-9.14
    environment:
      - LC_ALL: C.UTF-8
    branches:
      only:
        - hakyll
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-stack-work-{{ checksum "esimmler-com.cabal" }}
      - run:
          name: Build site
          command: |
            add-apt-repository ppa:tista/build
            apt-get update
            apt-get --yes install sassc python-pip libpython-dev
            pip install awscli
            stack setup
            stack build
            stack exec site rebuild
            cd _site; aws s3 sync . s3://esimmler.com/ --delete
      - save_cache:
          paths:
            - .stack-work
            - /root/.stack/
          key: v1-stack-work-{{ checksum "esimmler-com.cabal" }}
      - store_artifacts:
          path: _site
