version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    environment:
      - DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout

      - deploy:
          name: Publish
          command: |
            python publish.py
