version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    environment:
      - LC_ALL: C.UTF-8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-stack-work-{{ checksum "esimmler-com.cabal" }}

      - run:
          name: Install
          command: |
            wget -P /usr/local/bin https://github.com/tuhlmann/sassc-binaries/raw/master/v3.4.1/ubuntu/amd64/sassc
            chmod +x /usr/local/bin/sassc
            apt-get update
            apt-get --yes install python-pip libpython-dev
            pip install awscli

      - run:
          name: Build
          command: |
            stack setup
            stack build
            stack exec site rebuild

      - save_cache:
          paths:
            - .stack-work
            - /root/.stack/
          key: v1-stack-work-{{ checksum "esimmler-com.cabal" }}

      - store_artifacts:
          path: _site

      - deploy:
          name: Upload
          working_directory: _site
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              aws s3 sync . s3://staging.esimmler.com/pr-$CIRCLE_PR_NUMBER/ --delete
            fi

            if [ "$CIRCLE_BRANCH" == "master" ]; then
              aws s3 sync . s3://esimmler.com/ --delete
            else
              aws s3 sync . s3://staging.esimmler.com/$CIRCLE_BRANCH/ --delete
            fi

            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "http://staging.esimmler.com.s3-website-us-east-1.amazonaws.com/pr-$CIRCLE_PR_NUMBER/"
            fi

            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo "http://esimmler.com.s3-website-us-east-1.amazonaws.com/"
              echo "https://esimmler.com/"
            else
              echo "http://staging.esimmler.com.s3-website-us-east-1.amazonaws.com/$CIRCLE_BRANCH/"
            fi
