version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build
    environment:
      - LC_ALL: C.UTF-8
    branches:
      only:
        - hakyll
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-site-{{ checksum "esimmler-com.cabal" }}
      - run:
          name: Build site
          command: |
            stack setup
            stack build
            stack exec site rebuild
      - save_cache:
          paths:
            - .stack-work
            - /root/.stack/
          key: v1-stack-work-{{ checksum "esimmler-com.cabal" }}
      - store_artifacts:
          path: _site
