version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    environment:
      - DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout

      - run:
          name: Install
          command: |
            apt-get update
            apt-get install wget tar awscli -y
            wget -qO- http://github.com/getzola/zola/releases/download/v0.9.0/zola-v0.9.0-x86_64-unknown-linux-gnu.tar.gz | tar -xvz

      - deploy:
          name: Build and Upload
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              ./zola build --base-url http://staging.esimmler.com.s3-website-us-east-1.amazonaws.com/pr-$CIRCLE_PR_NUMBER
              cp public/rss.xml public/feed.atom
              aws s3 sync public s3://staging.esimmler.com/pr-$CIRCLE_PR_NUMBER/ --delete --acl public-read
            fi

            if [ "$CIRCLE_BRANCH" == "master" ]; then
              ./zola build
              cp public/rss.xml public/feed.atom
              aws s3 sync public s3://esimmler.com/ --delete --acl public-read
            else
              ./zola build --base-url http://staging.esimmler.com.s3-website-us-east-1.amazonaws.com/$CIRCLE_BRANCH
              cp public/rss.xml public/feed.atom
              aws s3 sync public s3://staging.esimmler.com/$CIRCLE_BRANCH/ --delete --acl public-read
            fi

            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "http://staging.esimmler.com.s3-website-us-east-1.amazonaws.com/pr-$CIRCLE_PR_NUMBER/"
            fi

            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo "http://esimmler.com.s3-website-us-east-1.amazonaws.com/"
              echo "https://esimmler.com/"
            else
              echo "http://staging.esimmler.com.s3-website-us-east-1.amazonaws.com/$CIRCLE_BRANCH/"
            fi
